
FROM node:14 as build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/dist/<nome-do-seu-projeto> /usr/share/nginx/html

EXPOSE 4200

CMD ["nginx", "-g", "daemon off;"]